# Generated by Django 5.2.15 on 2026-06-27 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Добавлено пользователем'), ('ai_chat', 'Получено из чата с ИИ'), ('admin', 'Добавлено администратором')], default='manual', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy_records', to='menu.allergen', verbose_name='Аллерген')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_records', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аллергия пользователя',
                'verbose_name_plural': 'Аллергии пользователей',
                'ordering': ['user', 'allergen__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'allergen'), name='unique_allergen_per_user')],
            },
        ),
    ]
