# Generated by Django 5.2.15 on 2026-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userallergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallergy',
            name='source',
            field=models.CharField(choices=[('manual', 'Добавлено пользователем'), ('ai_chat', 'Получено из диалога'), ('admin', 'Добавлено администратором')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
