# Generated by Django 5.2.15 on 2026-07-02 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_share_allergies_with_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllergyStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Old status')),
                ('new_status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], max_length=20, verbose_name='New status')),
                ('old_source', models.CharField(blank=True, choices=[('manual', 'Добавлено пользователем'), ('ai_chat', 'Получено из диалога'), ('admin', 'Добавлено администратором')], max_length=20, verbose_name='Old source')),
                ('new_source', models.CharField(choices=[('manual', 'Добавлено пользователем'), ('ai_chat', 'Получено из диалога'), ('admin', 'Добавлено администратором')], max_length=20, verbose_name='New source')),
                ('reason', models.CharField(max_length=80, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='accounts.userallergy', verbose_name='Allergy record')),
            ],
            options={
                'verbose_name': 'User allergy status change',
                'verbose_name_plural': 'User allergy status changes',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
