"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    os.getenv("SECRET_KEY", "django-insecure-change-this-in-production"),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", os.getenv("DEBUG", "False")).lower() in {
    "1",
    "true",
    "yes",
    "on",
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1"),
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "menu.apps.MenuConfig",
    "ai_assistant",
    "orders.apps.OrdersConfig",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "accounts.context_processors.account_identity",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Authentication

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_FORMS = {
    "login": "accounts.forms.LocalizedLoginForm",
    "signup": "accounts.forms.LocalizedSignupForm",
    "reset_password": "accounts.forms.LocalizedResetPasswordForm",
    "reset_password_from_key": "accounts.forms.LocalizedResetPasswordKeyForm",
}

LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "EMAIL_AUTHENTICATION": True,
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv("DB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "resto_db"),
            "USER": os.getenv("DB_USER", "resto_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", "resto_password"),
            "HOST": os.getenv("DB_HOST", "db"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "resto-ai-guards",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (User uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Gemini AI

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-3.5-flash",
)

GEMINI_FALLBACK_MODEL = os.getenv(
    "GEMINI_FALLBACK_MODEL",
    "gemini-2.5-flash",
)

AI_MAX_OUTPUT_TOKENS = int(
    os.getenv("AI_MAX_OUTPUT_TOKENS", "1000")
)

AI_HISTORY_LIMIT = int(
    os.getenv("AI_HISTORY_LIMIT", "12")
)

AI_MENU_CONTEXT_LIMIT = int(
    os.getenv("AI_MENU_CONTEXT_LIMIT", "80")
)

AI_HISTORY_RETENTION_DAYS = int(
    os.getenv("AI_HISTORY_RETENTION_DAYS", "180")
)

AI_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("AI_RATE_LIMIT_WINDOW_SECONDS", "60")
)

AI_RATE_LIMIT_IP_PER_MINUTE = int(
    os.getenv("AI_RATE_LIMIT_IP_PER_MINUTE", "30")
)

AI_RATE_LIMIT_GUEST_PER_MINUTE = int(
    os.getenv("AI_RATE_LIMIT_GUEST_PER_MINUTE", "6")
)

AI_RATE_LIMIT_USER_PER_MINUTE = int(
    os.getenv("AI_RATE_LIMIT_USER_PER_MINUTE", "12")
)

AI_DAILY_QUOTA_IP = int(
    os.getenv("AI_DAILY_QUOTA_IP", "120")
)

AI_DAILY_QUOTA_GUEST = int(
    os.getenv("AI_DAILY_QUOTA_GUEST", "25")
)

AI_DAILY_QUOTA_USER = int(
    os.getenv("AI_DAILY_QUOTA_USER", "80")
)

AI_DAILY_TOKEN_BUDGET_IP = int(
    os.getenv("AI_DAILY_TOKEN_BUDGET_IP", "160000")
)

AI_DAILY_TOKEN_BUDGET_GUEST = int(
    os.getenv("AI_DAILY_TOKEN_BUDGET_GUEST", "30000")
)

AI_DAILY_TOKEN_BUDGET_USER = int(
    os.getenv("AI_DAILY_TOKEN_BUDGET_USER", "100000")
)

AI_ESTIMATED_RESPONSE_TOKENS = int(
    os.getenv("AI_ESTIMATED_RESPONSE_TOKENS", "600")
)

AI_ESTIMATED_COST_MICROS_PER_1000_TOKENS = int(
    os.getenv("AI_ESTIMATED_COST_MICROS_PER_1000_TOKENS", "0")
)

AI_DAILY_COST_BUDGET_MICROS_IP = int(
    os.getenv("AI_DAILY_COST_BUDGET_MICROS_IP", "0")
)

AI_DAILY_COST_BUDGET_MICROS_GUEST = int(
    os.getenv("AI_DAILY_COST_BUDGET_MICROS_GUEST", "0")
)

AI_DAILY_COST_BUDGET_MICROS_USER = int(
    os.getenv("AI_DAILY_COST_BUDGET_MICROS_USER", "0")
)

AI_STREAM_CONCURRENCY_IP = int(
    os.getenv("AI_STREAM_CONCURRENCY_IP", "5")
)

AI_STREAM_CONCURRENCY_GUEST = int(
    os.getenv("AI_STREAM_CONCURRENCY_GUEST", "1")
)

AI_STREAM_CONCURRENCY_USER = int(
    os.getenv("AI_STREAM_CONCURRENCY_USER", "2")
)

AI_STREAM_LOCK_TIMEOUT_SECONDS = int(
    os.getenv("AI_STREAM_LOCK_TIMEOUT_SECONDS", "180")
)

AI_ABUSE_BLOCK_THRESHOLD = int(
    os.getenv("AI_ABUSE_BLOCK_THRESHOLD", "8")
)

AI_ABUSE_BLOCK_SECONDS = int(
    os.getenv("AI_ABUSE_BLOCK_SECONDS", "600")
)

AI_TRUST_X_FORWARDED_FOR = os.getenv(
    "AI_TRUST_X_FORWARDED_FOR",
    "False",
).lower() in {"1", "true", "yes", "on"}
