"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from ipaddress import ip_network
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _parse_startup_bool(name, value):
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(
        f"{name} must be a boolean value: true/false, yes/no, on/off, or 1/0."
    )


def should_load_dotenv():
    """Return True when local .env loading is safe for this process.

    Development commands should stay convenient, so .env is loaded by default.
    A production process that already declares DJANGO_ENV=production must not
    silently import local development values from a stray project-root .env file.
    Set RESTO_LOAD_DOTENV=true in the real process environment only when a
    production deployment intentionally uses a dotenv file as its secret source.
    """

    explicit = os.getenv("RESTO_LOAD_DOTENV")
    if explicit is not None and explicit != "":
        return _parse_startup_bool("RESTO_LOAD_DOTENV", explicit)

    return os.getenv("DJANGO_ENV", "").strip().lower() != "production"


if should_load_dotenv():
    load_dotenv(BASE_DIR / ".env")


def env_value(name, default=None, *, required=False):
    value = os.getenv(name)
    if value is None or value == "":
        if required:
            raise ImproperlyConfigured(f"{name} environment variable is required.")
        return default
    return value


def env_bool(name, default=False, *, required=False):
    value = env_value(name, required=required)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(
        f"{name} must be a boolean value: true/false, yes/no, on/off, or 1/0."
    )


def env_int(name, default, *, required=False):
    value = env_value(name, required=required)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc


def env_list(name, default="", *, required=False):
    value = env_value(name, default, required=required)
    return [item.strip() for item in value.split(",") if item.strip()]


DJANGO_ENV = env_value("DJANGO_ENV", "development").lower()
IS_PRODUCTION = DJANGO_ENV == "production"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_value(
    "DJANGO_SECRET_KEY",
    os.getenv("SECRET_KEY", "django-insecure-local-development-only"),
    required=IS_PRODUCTION,
)

INSECURE_SECRET_KEYS = {
    "django-insecure-change-me",
    "django-insecure-change-this-value",
    "django-insecure-change-this-in-production",
    "django-insecure-local-development-only",
}

if IS_PRODUCTION and SECRET_KEY in INSECURE_SECRET_KEYS:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set to a unique, non-example value in production."
    )

TABLE_QR_TOKEN_ENCRYPTION_KEY = env_value(
    "TABLE_QR_TOKEN_ENCRYPTION_KEY",
    SECRET_KEY if not IS_PRODUCTION else None,
    required=IS_PRODUCTION,
)
TABLE_QR_TOKEN_ENCRYPTION_KEY = str(TABLE_QR_TOKEN_ENCRYPTION_KEY or "").strip()
TABLE_QR_TOKEN_ENCRYPTION_FALLBACK_KEYS = env_list(
    "TABLE_QR_TOKEN_ENCRYPTION_FALLBACK_KEYS",
    "",
)

if IS_PRODUCTION and not TABLE_QR_TOKEN_ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        "TABLE_QR_TOKEN_ENCRYPTION_KEY environment variable is required."
    )

if IS_PRODUCTION and TABLE_QR_TOKEN_ENCRYPTION_KEY == SECRET_KEY:
    raise ImproperlyConfigured(
        "TABLE_QR_TOKEN_ENCRYPTION_KEY must be independent from DJANGO_SECRET_KEY."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool(
    "DJANGO_DEBUG",
    os.getenv("DEBUG", "False").lower() in {"1", "true", "yes", "on"},
    required=IS_PRODUCTION,
)

if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DJANGO_DEBUG must be False in production.")

# Site URL is used to build public absolute URLs, including printable table QR
# links and OAuth callbacks.
SITE_URL = env_value("SITE_URL", "http://localhost:8000").rstrip("/")
_SITE_URL_PARTS = urlparse(SITE_URL)

if (
    _SITE_URL_PARTS.scheme not in {"http", "https"}
    or not _SITE_URL_PARTS.netloc
):
    raise ImproperlyConfigured("SITE_URL must be an absolute http(s) URL.")

if IS_PRODUCTION and _SITE_URL_PARTS.scheme != "https":
    raise ImproperlyConfigured("SITE_URL must use https in production.")

ACCOUNT_DEFAULT_HTTP_PROTOCOL = env_value(
    "DJANGO_ACCOUNT_DEFAULT_HTTP_PROTOCOL",
    _SITE_URL_PARTS.scheme,
).lower()

if ACCOUNT_DEFAULT_HTTP_PROTOCOL not in {"http", "https"}:
    raise ImproperlyConfigured(
        "DJANGO_ACCOUNT_DEFAULT_HTTP_PROTOCOL must be either http or https."
    )

if IS_PRODUCTION and ACCOUNT_DEFAULT_HTTP_PROTOCOL != "https":
    raise ImproperlyConfigured(
        "DJANGO_ACCOUNT_DEFAULT_HTTP_PROTOCOL must be https in production."
    )

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1"),
    required=IS_PRODUCTION,
)

if IS_PRODUCTION and "*" in ALLOWED_HOSTS:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must not contain '*' in production.")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if not IS_PRODUCTION:
    _local_csrf_port = env_value("APP_PORT", "8000")
    for _local_csrf_origin in (
        f"http://localhost:{_local_csrf_port}",
        f"http://127.0.0.1:{_local_csrf_port}",
        f"http://0.0.0.0:{_local_csrf_port}",
    ):
        if _local_csrf_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_local_csrf_origin)

TRUST_PROXY_HEADERS = env_bool(
    "DJANGO_TRUST_PROXY_HEADERS",
    env_bool("RATE_LIMIT_TRUST_PROXY_HEADERS", False),
)
TRUSTED_PROXY_CIDRS = env_list("DJANGO_TRUSTED_PROXY_CIDRS", "")

for trusted_proxy_cidr in TRUSTED_PROXY_CIDRS:
    try:
        ip_network(trusted_proxy_cidr, strict=False)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f"Invalid network in DJANGO_TRUSTED_PROXY_CIDRS: {trusted_proxy_cidr}"
        ) from exc

if IS_PRODUCTION and TRUST_PROXY_HEADERS and not TRUSTED_PROXY_CIDRS:
    raise ImproperlyConfigured(
        "DJANGO_TRUSTED_PROXY_CIDRS is required when proxy headers are trusted."
    )

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", IS_PRODUCTION)
CSRF_ALLOW_NULL_ORIGIN = env_bool("DJANGO_CSRF_ALLOW_NULL_ORIGIN", DEBUG)

if DEBUG:
    # Local development normally runs over plain HTTP. Secure cookies or forced
    # SSL redirects make the CSRF/session cookies invisible to localhost forms
    # and OAuth state checks, which surfaces as Google-login CSRF failures.
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

SECURE_HSTS_SECONDS = env_int(
    "DJANGO_SECURE_HSTS_SECONDS",
    3600 if IS_PRODUCTION else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

USE_SECURE_PROXY_SSL_HEADER = env_bool(
    "DJANGO_SECURE_PROXY_SSL_HEADER",
    IS_PRODUCTION,
)
if IS_PRODUCTION and USE_SECURE_PROXY_SSL_HEADER and not TRUST_PROXY_HEADERS:
    raise ImproperlyConfigured(
        "DJANGO_TRUST_PROXY_HEADERS must be enabled when "
        "DJANGO_SECURE_PROXY_SSL_HEADER is enabled in production."
    )
if USE_SECURE_PROXY_SSL_HEADER:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = env_value("DJANGO_REFERRER_POLICY", "same-origin")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "DENY"
SECURE_REDIRECT_EXEMPT = [r"^health/(live|ready)/$", r"^healthz/$"]

SECURITY_POLICY_HEADERS_ENABLED = env_bool(
    "DJANGO_SECURITY_POLICY_HEADERS_ENABLED",
    True,
)
_content_security_policy_parts = [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com data:",
    "img-src 'self' data: blob:",
    "connect-src 'self'",
    "media-src 'self'",
    "manifest-src 'self'",
    "worker-src 'self' blob:",
    "form-action 'self' https://accounts.google.com",
]
if IS_PRODUCTION:
    _content_security_policy_parts.append("upgrade-insecure-requests")
CONTENT_SECURITY_POLICY = "; ".join(_content_security_policy_parts)
PERMISSIONS_POLICY = env_value(
    "DJANGO_PERMISSIONS_POLICY",
    "camera=(), microphone=(), geolocation=(), usb=(), browsing-topics=()",
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "menu.apps.MenuConfig",
    "ai_assistant",
    "orders.apps.OrdersConfig",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

MIDDLEWARE = [
    "config.proxy.TrustedProxyHeadersMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "config.security.SecurityPolicyMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "config.csrf.RestoCsrfViewMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    "config.rate_limit.RateLimitMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

USE_WHITENOISE = env_bool("DJANGO_USE_WHITENOISE", not DEBUG)

if USE_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "accounts.context_processors.account_identity",
                "config.context_processors.ui_preferences",
                "config.context_processors.oauth_providers",
                "menu.context_processors.remembered_table_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Authentication

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_FORMS = {
    "login": "accounts.forms.LocalizedLoginForm",
    "signup": "accounts.forms.LocalizedSignupForm",
    "reset_password": "accounts.forms.LocalizedResetPasswordForm",
    "reset_password_from_key": "accounts.forms.LocalizedResetPasswordKeyForm",
}

LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/account/"
LOGOUT_REDIRECT_URL = "/"

EMAIL_BACKEND = env_value(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
    required=IS_PRODUCTION,
)

UNSAFE_PRODUCTION_EMAIL_BACKENDS = {
    "django.core.mail.backends.console.EmailBackend",
    "django.core.mail.backends.locmem.EmailBackend",
    "django.core.mail.backends.dummy.EmailBackend",
    "django.core.mail.backends.filebased.EmailBackend",
}

if IS_PRODUCTION and EMAIL_BACKEND in UNSAFE_PRODUCTION_EMAIL_BACKENDS:
    raise ImproperlyConfigured(
        "EMAIL_BACKEND must deliver email in production; console, locmem, dummy, "
        "and filebased backends are not allowed."
    )

EMAIL_HOST = env_value(
    "EMAIL_HOST",
    "",
    required=IS_PRODUCTION
    and EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = env_value("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env_value("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 10)
DEFAULT_FROM_EMAIL = env_value(
    "DEFAULT_FROM_EMAIL",
    "webmaster@localhost",
    required=IS_PRODUCTION,
)
SERVER_EMAIL = env_value("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = env_value("EMAIL_SUBJECT_PREFIX", "[Caesar & Company] ")

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured("EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.")

if (
    IS_PRODUCTION
    and EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend"
    and not (EMAIL_USE_TLS or EMAIL_USE_SSL)
):
    raise ImproperlyConfigured("SMTP email must use TLS or SSL in production.")

if IS_PRODUCTION and DEFAULT_FROM_EMAIL.endswith("@localhost"):
    raise ImproperlyConfigured(
        "DEFAULT_FROM_EMAIL must be a real sender address in production."
    )

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

GOOGLE_OAUTH_PLACEHOLDER_PREFIXES = ("replace-with-", "change-me")
GOOGLE_OAUTH_CLIENT_ID = env_value("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = env_value("GOOGLE_OAUTH_CLIENT_SECRET", "")


def is_configured_secret(value):
    normalized = str(value or "").strip()
    if not normalized:
        return False

    return not any(
        normalized.lower().startswith(prefix)
        for prefix in GOOGLE_OAUTH_PLACEHOLDER_PREFIXES
    )


GOOGLE_OAUTH_ENABLED = env_bool(
    "GOOGLE_OAUTH_ENABLED",
    is_configured_secret(GOOGLE_OAUTH_CLIENT_ID)
    and is_configured_secret(GOOGLE_OAUTH_CLIENT_SECRET),
)

if GOOGLE_OAUTH_ENABLED and not (
    is_configured_secret(GOOGLE_OAUTH_CLIENT_ID)
    and is_configured_secret(GOOGLE_OAUTH_CLIENT_SECRET)
):
    raise ImproperlyConfigured(
        "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET must be set "
        "to real values when GOOGLE_OAUTH_ENABLED is true."
    )

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": GOOGLE_OAUTH_CLIENT_ID if GOOGLE_OAUTH_ENABLED else "",
            "secret": GOOGLE_OAUTH_CLIENT_SECRET if GOOGLE_OAUTH_ENABLED else "",
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "EMAIL_AUTHENTICATION": True,
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SQLITE_DATABASE_PATH = env_value("SQLITE_DATABASE_PATH", "")

if SQLITE_DATABASE_PATH:
    if IS_PRODUCTION:
        raise ImproperlyConfigured("SQLITE_DATABASE_PATH must not be used in production.")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_DATABASE_PATH,
        }
    }
elif os.getenv("DB_HOST"):
    db_password = env_value("DB_PASSWORD", required=True)
    if IS_PRODUCTION and db_password in {"resto_password", "password", "change-me"}:
        raise ImproperlyConfigured(
            "DB_PASSWORD must be set to a unique, non-example value in production."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env_value("DB_NAME", "resto_db", required=IS_PRODUCTION),
            "USER": env_value("DB_USER", "resto_user", required=IS_PRODUCTION),
            "PASSWORD": db_password,
            "HOST": env_value("DB_HOST", "db", required=IS_PRODUCTION),
            "PORT": env_value("DB_PORT", "5432"),
        }
    }
else:
    if IS_PRODUCTION:
        raise ImproperlyConfigured("DB_HOST is required in production.")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

REDIS_URL = os.getenv("REDIS_URL", "")

if IS_PRODUCTION and not REDIS_URL:
    raise ImproperlyConfigured(
        "REDIS_URL is required in production so rate limits are shared across workers."
    )

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "resto-ai-guards",
        }
    }


RATE_LIMIT_ENABLED = env_bool("RATE_LIMIT_ENABLED", True)
# Backward-compatible aliases. Request identity now uses one validated proxy policy.
RATE_LIMIT_TRUST_PROXY_HEADERS = TRUST_PROXY_HEADERS
AI_TRUST_X_FORWARDED_FOR = TRUST_PROXY_HEADERS
RATE_LIMIT_CACHE_FAILURE_RETRY_AFTER = env_int(
    "RATE_LIMIT_CACHE_FAILURE_RETRY_AFTER",
    5,
)
RATE_LIMIT_MESSAGE = env_value(
    "RATE_LIMIT_MESSAGE",
    "Too many requests. Please try again later.",
)


def rate_limit(name, default, window):
    return {
        "name": name,
        "limit": env_int(f"RATE_LIMIT_{name.upper()}", default),
        "window": window,
    }


RATE_LIMIT_RULES = {
    "account_login": {
        "cache_failure": "closed",
        "methods": ["POST"],
        "identity": "ip+field",
        "field": "login",
        "limits": [
            rate_limit("login_per_minute", 8, 60),
            rate_limit("login_per_hour", 40, 3600),
        ],
    },
    "account_signup": {
        "cache_failure": "closed",
        "methods": ["POST"],
        "identity": "ip+field",
        "field": "email",
        "limits": [
            rate_limit("signup_per_minute", 5, 60),
            rate_limit("signup_per_hour", 20, 3600),
        ],
    },
    "account_reset_password": {
        "cache_failure": "closed",
        "methods": ["POST"],
        "identity": "ip+field",
        "field": "email",
        "limits": [
            rate_limit("password_reset_per_minute", 3, 60),
            rate_limit("password_reset_per_hour", 10, 3600),
        ],
    },
    "account_reset_password_from_key": {
        "cache_failure": "closed",
        "methods": ["POST"],
        "identity": "ip",
        "limits": [
            rate_limit("password_reset_confirm_per_minute", 6, 60),
            rate_limit("password_reset_confirm_per_hour", 30, 3600),
        ],
    },
    "google_login": {
        "cache_failure": "closed",
        "methods": ["POST"],
        "identity": "ip",
        "limits": [
            rate_limit("google_login_per_minute", 10, 60),
            rate_limit("google_login_per_hour", 60, 3600),
        ],
    },
    "ai_assistant:ask": {
        "cache_failure": "closed",
        "methods": ["POST"],
        "identity": "ip+actor",
        "limits": [
            rate_limit("ai_ask_per_minute", 20, 60),
            rate_limit("ai_ask_per_hour", 120, 3600),
        ],
    },
    "menu:table_menu": {
        "cache_failure": "open",
        "methods": ["GET"],
        "identity": "ip",
        "limits": [
            rate_limit("qr_menu_per_minute", 30, 60),
            rate_limit("qr_menu_per_hour", 300, 3600),
        ],
    },
    "orders:quote": {
        "cache_failure": "open",
        "methods": ["POST"],
        "identity": "ip+actor",
        "limits": [
            rate_limit("order_quote_per_minute", 120, 60),
            rate_limit("order_quote_per_hour", 1000, 3600),
        ],
    },
    "orders:create": {
        "cache_failure": "open",
        "methods": ["POST"],
        "identity": "ip+actor",
        "limits": [
            rate_limit("order_create_per_minute", 20, 60),
            rate_limit("order_create_per_hour", 100, 3600),
        ],
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = env_value("DJANGO_TIME_ZONE", "Europe/Moscow")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_STATICFILES_BACKEND = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if IS_PRODUCTION
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)
STATICFILES_BACKEND = env_value(
    "DJANGO_STATICFILES_BACKEND",
    DEFAULT_STATICFILES_BACKEND,
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}

WHITENOISE_MAX_AGE = 31536000 if IS_PRODUCTION else 0

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Gemini AI

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-3.5-flash",
)

GEMINI_FALLBACK_MODEL = os.getenv(
    "GEMINI_FALLBACK_MODEL",
    "gemini-2.5-flash",
)

AI_MAX_REQUEST_BODY_BYTES = env_int("AI_MAX_REQUEST_BODY_BYTES", 32768)

AI_MAX_OUTPUT_TOKENS = int(
    os.getenv("AI_MAX_OUTPUT_TOKENS", "1000")
)

AI_HISTORY_LIMIT = int(
    os.getenv("AI_HISTORY_LIMIT", "12")
)

AI_MENU_CONTEXT_LIMIT = int(
    os.getenv("AI_MENU_CONTEXT_LIMIT", "80")
)

AI_HISTORY_RETENTION_DAYS = int(
    os.getenv("AI_HISTORY_RETENTION_DAYS", "180")
)

AI_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("AI_RATE_LIMIT_WINDOW_SECONDS", "60")
)

AI_RATE_LIMIT_IP_PER_MINUTE = int(
    os.getenv("AI_RATE_LIMIT_IP_PER_MINUTE", "30")
)

AI_RATE_LIMIT_GUEST_PER_MINUTE = int(
    os.getenv("AI_RATE_LIMIT_GUEST_PER_MINUTE", "6")
)

AI_RATE_LIMIT_USER_PER_MINUTE = int(
    os.getenv("AI_RATE_LIMIT_USER_PER_MINUTE", "12")
)

AI_DAILY_QUOTA_IP = int(
    os.getenv("AI_DAILY_QUOTA_IP", "120")
)

AI_DAILY_QUOTA_GUEST = int(
    os.getenv("AI_DAILY_QUOTA_GUEST", "25")
)

AI_DAILY_QUOTA_USER = int(
    os.getenv("AI_DAILY_QUOTA_USER", "80")
)

AI_DAILY_TOKEN_BUDGET_IP = int(
    os.getenv("AI_DAILY_TOKEN_BUDGET_IP", "160000")
)

AI_DAILY_TOKEN_BUDGET_GUEST = int(
    os.getenv("AI_DAILY_TOKEN_BUDGET_GUEST", "30000")
)

AI_DAILY_TOKEN_BUDGET_USER = int(
    os.getenv("AI_DAILY_TOKEN_BUDGET_USER", "100000")
)

AI_ESTIMATED_RESPONSE_TOKENS = int(
    os.getenv("AI_ESTIMATED_RESPONSE_TOKENS", "600")
)

AI_ESTIMATED_COST_MICROS_PER_1000_TOKENS = int(
    os.getenv("AI_ESTIMATED_COST_MICROS_PER_1000_TOKENS", "0")
)

AI_DAILY_COST_BUDGET_MICROS_IP = int(
    os.getenv("AI_DAILY_COST_BUDGET_MICROS_IP", "0")
)

AI_DAILY_COST_BUDGET_MICROS_GUEST = int(
    os.getenv("AI_DAILY_COST_BUDGET_MICROS_GUEST", "0")
)

AI_DAILY_COST_BUDGET_MICROS_USER = int(
    os.getenv("AI_DAILY_COST_BUDGET_MICROS_USER", "0")
)

AI_STREAM_CONCURRENCY_IP = int(
    os.getenv("AI_STREAM_CONCURRENCY_IP", "5")
)

AI_STREAM_CONCURRENCY_GUEST = int(
    os.getenv("AI_STREAM_CONCURRENCY_GUEST", "1")
)

AI_STREAM_CONCURRENCY_USER = int(
    os.getenv("AI_STREAM_CONCURRENCY_USER", "2")
)

AI_STREAM_LOCK_TIMEOUT_SECONDS = int(
    os.getenv("AI_STREAM_LOCK_TIMEOUT_SECONDS", "180")
)

AI_SESSION_LOCK_TIMEOUT_SECONDS = int(
    os.getenv("AI_SESSION_LOCK_TIMEOUT_SECONDS", str(AI_STREAM_LOCK_TIMEOUT_SECONDS))
)

AI_PROVIDER_TIMEOUT_SECONDS = env_int("AI_PROVIDER_TIMEOUT_SECONDS", 45)
AI_REQUEST_LOCK_TIMEOUT_SECONDS = env_int("AI_REQUEST_LOCK_TIMEOUT_SECONDS", 30)
AI_REQUEST_STALE_SECONDS = env_int("AI_REQUEST_STALE_SECONDS", 180)
AI_QUOTA_LOCK_TIMEOUT_SECONDS = env_int("AI_QUOTA_LOCK_TIMEOUT_SECONDS", 5)
AI_QUOTA_LOCK_RETRY_AFTER_SECONDS = env_int(
    "AI_QUOTA_LOCK_RETRY_AFTER_SECONDS",
    1,
)
AI_STREAM_HEARTBEAT_SECONDS = env_int("AI_STREAM_HEARTBEAT_SECONDS", 5)

for setting_name, setting_value in {
    "AI_PROVIDER_TIMEOUT_SECONDS": AI_PROVIDER_TIMEOUT_SECONDS,
    "AI_REQUEST_LOCK_TIMEOUT_SECONDS": AI_REQUEST_LOCK_TIMEOUT_SECONDS,
    "AI_REQUEST_STALE_SECONDS": AI_REQUEST_STALE_SECONDS,
    "AI_QUOTA_LOCK_TIMEOUT_SECONDS": AI_QUOTA_LOCK_TIMEOUT_SECONDS,
    "AI_QUOTA_LOCK_RETRY_AFTER_SECONDS": AI_QUOTA_LOCK_RETRY_AFTER_SECONDS,
    "AI_STREAM_HEARTBEAT_SECONDS": AI_STREAM_HEARTBEAT_SECONDS,
}.items():
    if setting_value <= 0:
        raise ImproperlyConfigured(f"{setting_name} must be greater than zero.")

AI_ABUSE_BLOCK_THRESHOLD = int(
    os.getenv("AI_ABUSE_BLOCK_THRESHOLD", "8")
)

AI_ABUSE_BLOCK_SECONDS = int(
    os.getenv("AI_ABUSE_BLOCK_SECONDS", "600")
)


# Optional payment-provider settings. Real payments are not invoked by the
# current checkout flow, but these values keep the helper ready for future use.
YOOKASSA_SHOP_ID = env_value("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = env_value("YOOKASSA_SECRET_KEY", "")
YOOKASSA_MOCK = env_bool("YOOKASSA_MOCK", False)

if IS_PRODUCTION and YOOKASSA_MOCK:
    raise ImproperlyConfigured("YOOKASSA_MOCK must be False in production.")
