# Generated by Django 5.2.15 on 2026-07-03 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_structured_recommendations'),
        ('orders', '0009_order_mode_and_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusageevent',
            name='actual_cost_micros',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusageevent',
            name='actual_prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusageevent',
            name='actual_response_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusageevent',
            name='actual_total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusageevent',
            name='provider_response_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='aiusageevent',
            name='status',
            field=models.CharField(choices=[('started', 'Начат'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('canceled', 'Отменен клиентом'), ('throttled', 'Ограничен'), ('fallback', 'Локальный fallback')], db_index=True, default='started', max_length=20),
        ),
        migrations.CreateModel(
            name='AIRequestRecord',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Client request ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('request_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Выполняется'), ('completed', 'Завершен'), ('fallback', 'Локальный fallback'), ('failed', 'Ошибка'), ('canceled', 'Отменен клиентом')], db_index=True, default='processing', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('is_stream', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assistant_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_request', to='ai_assistant.chatmessage')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_records', to='ai_assistant.chatsession')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_records', to='orders.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_records', to=settings.AUTH_USER_MODEL)),
                ('user_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='originating_request', to='ai_assistant.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiusageevent',
            name='request_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_event', to='ai_assistant.airequestrecord'),
        ),
        migrations.AddIndex(
            model_name='airequestrecord',
            index=models.Index(fields=['status', 'updated_at'], name='ai_req_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestrecord',
            index=models.Index(fields=['user', 'created_at'], name='ai_req_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestrecord',
            index=models.Index(fields=['session_key', 'created_at'], name='ai_req_session_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='airequestrecord',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('session_key', ''), _negated=True), _connector='OR'), name='ai_request_owner_present'),
        ),
        migrations.AddConstraint(
            model_name='airequestrecord',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        status__in=['completed', 'fallback'],
                        assistant_message__isnull=False,
                        completed_at__isnull=False,
                    )
                    | models.Q(
                        status='processing',
                        assistant_message__isnull=True,
                        completed_at__isnull=True,
                    )
                    | models.Q(
                        status__in=['failed', 'canceled'],
                        assistant_message__isnull=True,
                        completed_at__isnull=False,
                    )
                ),
                name='ai_request_completion_consistent',
            ),
        ),
    ]
