# Generated by Django 5.2.15 on 2026-06-27 13:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.SlugField(help_text='Например: milk, egg, peanut, gluten', max_length=100, unique=True, verbose_name='Системный код')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='dishes/%Y/%m/', verbose_name='Фотография')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('serving_weight_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес порции, г')),
                ('calories_kcal_per_serving', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории на порцию, ккал')),
                ('proteins_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Белки на порцию, г')),
                ('fats_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Жиры на порцию, г')),
                ('carbohydrates_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Углеводы на порцию, г')),
                ('preparation_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления, мин')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menu.category', verbose_name='Категория')),
                ('may_contain_allergens', models.ManyToManyField(blank=True, related_name='may_contain_dishes', to='menu.allergen', verbose_name='Может содержать следы аллергенов')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('allergens', models.ManyToManyField(blank=True, related_name='ingredients', to='menu.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Количество')),
                ('unit', models.CharField(blank=True, choices=[('g', 'г'), ('ml', 'мл'), ('piece', 'шт.'), ('tbsp', 'ст. ложка'), ('tsp', 'ч. ложка'), ('portion', 'порция'), ('to_taste', 'по вкусу')], max_length=20, verbose_name='Единица измерения')),
                ('can_be_removed', models.BooleanField(default=False, verbose_name='Можно убрать из блюда')),
                ('notes', models.CharField(blank=True, help_text='Например: добавляется при подаче', max_length=255, verbose_name='Примечание')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='menu.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_ingredients', to='menu.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент блюда',
                'verbose_name_plural': 'Ингредиенты блюда',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='menu.DishIngredient', to='menu.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='unique_ingredient_per_dish'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_active', 'is_available'], name='dish_active_available_idx'),
        ),
    ]
