# Generated by Django 5.2.15 on 2026-07-01 16:58

import django.db.models.deletion
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_link_caesar_sauce_allergens'),
        ('orders', '0002_order_idempotency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['restaurant__name', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='dish',
            name='dish_active_available_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=menu.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='orders.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=menu.models.get_default_restaurant_id, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='orders.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['restaurant', 'is_active', 'is_available'], name='dish_rest_active_avail_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_category_name_per_restaurant'),
        ),
    ]
