# Generated by Django 5.2.15 on 2026-07-03 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_allergen_review_metadata(apps, schema_editor):
    Dish = apps.get_model("menu", "Dish")
    DishAllergen = apps.get_model("menu", "DishAllergen")
    now = timezone.now()

    DishAllergen.objects.filter(
        verification_status__in=["verified", "rejected"],
    ).update(
        reviewed_recipe_revision=1,
        reviewed_at=now,
    )

    for dish in Dish.objects.all().iterator():
        statuses = set(
            DishAllergen.objects.filter(dish_id=dish.pk).values_list(
                "verification_status",
                flat=True,
            )
        )
        if "suggested" in statuses:
            review_status = "needs_review"
        elif statuses.intersection({"verified", "rejected"}):
            review_status = "partial"
        else:
            review_status = "unknown"

        Dish.objects.filter(pk=dish.pk).update(
            allergen_review_status=review_status,
            allergen_reviewed_revision=None,
            allergen_reviewed_at=None,
            allergen_reviewed_by=None,
        )


def reverse_allergen_review_metadata(apps, schema_editor):
    DishAllergen = apps.get_model("menu", "DishAllergen")
    DishAllergen.objects.update(
        reviewed_recipe_revision=None,
        reviewed_at=None,
        reviewed_by=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_unify_dish_allergens'),
        ('orders', '0009_order_mode_and_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAllergenReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verified', 'Аллерген подтверждён'), ('rejected', 'Аллерген отклонён'), ('invalidated', 'Проверка устарела'), ('review_completed', 'Проверка блюда завершена'), ('review_reopened', 'Проверка блюда открыта повторно'), ('suggested', 'Создано предложение')], db_index=True, max_length=32, verbose_name='Действие')),
                ('recipe_revision', models.PositiveIntegerField(verbose_name='Версия рецепта')),
                ('relation_type', models.CharField(blank=True, choices=[('contains', 'Содержит'), ('may_contain', 'Может содержать'), ('cross_contamination', 'Может содержать следы')], max_length=32, verbose_name='Тип связи')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Событие проверки аллергенов',
                'verbose_name_plural': 'История проверки аллергенов',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_review_notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий к проверке аллергенов'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_review_status',
            field=models.CharField(choices=[('unknown', 'Не проверено'), ('needs_review', 'Требует проверки'), ('partial', 'Проверено частично'), ('complete', 'Проверено полностью')], db_index=True, default='unknown', max_length=20, verbose_name='Полнота проверки аллергенов'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Аллергены проверены'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dish_allergen_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Проверил аллергены блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_reviewed_revision',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Проверенная версия рецепта'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_revision',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Увеличивается при изменении состава блюда. Используется для проверки актуальности аллергенных данных.', verbose_name='Версия рецепта'),
        ),
        migrations.AddField(
            model_name='dishallergen',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='dishallergen',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dish_allergen_links', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='dishallergen',
            name='reviewed_recipe_revision',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Проверено для версии рецепта'),
        ),
        migrations.RunPython(
            backfill_allergen_review_metadata,
            reverse_allergen_review_metadata,
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(('recipe_revision__gte', 1)), name='dish_recipe_revision_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allergen_review_status', 'complete'), _negated=True), models.Q(('allergen_reviewed_revision', models.F('recipe_revision')), ('allergen_reviewed_at__isnull', False)), _connector='OR'), name='dish_complete_review_has_metadata'),
        ),
        migrations.AddConstraint(
            model_name='dishallergen',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_recipe_revision__isnull', True), ('verification_status', 'suggested')), models.Q(('reviewed_at__isnull', False), ('reviewed_recipe_revision__isnull', False), ('verification_status__in', ['verified', 'rejected'])), _connector='OR'), name='dish_allergen_review_metadata_matches_status'),
        ),
        migrations.AddField(
            model_name='dishallergenreviewevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_allergen_review_events', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='dishallergenreviewevent',
            name='allergen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_review_events', to='menu.allergen', verbose_name='Аллерген'),
        ),
        migrations.AddField(
            model_name='dishallergenreviewevent',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_review_events', to='menu.dish', verbose_name='Блюдо'),
        ),
        migrations.AddIndex(
            model_name='dishallergenreviewevent',
            index=models.Index(fields=['dish', 'recipe_revision', 'created_at'], name='dish_allergen_review_event_idx'),
        ),
    ]
