# Generated by Django 5.2.15 on 2026-07-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.PositiveIntegerField(default=0, verbose_name='Версия'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтвержден'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('served', 'Подан'), ('completed', 'Завершен'), ('canceled', 'Отменен')], max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтвержден'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('served', 'Подан'), ('completed', 'Завершен'), ('canceled', 'Отменен')], max_length=20, verbose_name='В статус')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('order_version', models.PositiveIntegerField(verbose_name='Версия заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='order_status_history_idx')],
            },
        ),
    ]
